apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: v2
  name: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      version: v2
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
        version: v2
    spec:
      initContainers:
      - image: busybox
        name: init
        command: [ "sh", "-c", "echo \"<h2 style='background-color:${COLOR}'>${COLOR} APP V2 Canary background-color</h2>\" > /data/index.html" ]
        volumeMounts:
        - name: index
          mountPath: /data
        env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: webcolor
              key: v2
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index
          mountPath: /usr/local/apache2/htdocs
        resources: {}
      volumes:
      - name: index
        emptyDir: {}
